package com.msm.chatapp.DataBase;

import com.msm.chatapp.DataModels.ChatModel;
import com.msm.chatapp.DataModels.MessageModel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatDB {

    public static List<ChatModel> chatModelList;

    public static void InitiateDB(){
        chatModelList=new ArrayList<>();
        for(int i=0;i<10;i++){
            ChatModel chatModel;
            MessageModel msg;
            Date date;
            chatModel=new ChatModel();
            chatModel.setId(String.valueOf(i)+"1");
            chatModel.setName("Manas"+i);
            msg=new MessageModel();
            msg.setMsg("Hello");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(10)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Hi");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(9)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("How are you doing?");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(8)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("I am fine.");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(7)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("What about you?");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(6)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Ya!I am fine too");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(5)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            chatModelList.add(chatModel);
            chatModel=new ChatModel();
            chatModel.setId(String.valueOf(i)+"1");
            chatModel.setName("Meghana"+i);
            msg=new MessageModel();
            msg.setMsg("Hello");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(10)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Hi");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(9)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("How are you doing?");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(8)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("I am fine.");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(7)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("What about you?");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(6)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Ya!I am fine too");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(5)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            chatModelList.add(chatModel);
            chatModel=new ChatModel();
            chatModel.setId(String.valueOf(i)+"1");
            chatModel.setName("Rohith"+i);
            msg=new MessageModel();
            msg.setMsg("Hello");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(10)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Hi");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(9)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("How are you doing?");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(8)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("I am fine.");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(7)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("What about you?");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(6)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Ya!I am fine too");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(5)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            chatModelList.add(chatModel);
            chatModel=new ChatModel();
            chatModel.setId(String.valueOf(i)+"1");
            chatModel.setName("Rakshith"+i);
            msg=new MessageModel();
            msg.setMsg("Hello");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(10)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Hi");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(9)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("How are you doing?");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(8)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("I am fine.");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(7)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("What about you?");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(6)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Ya!I am fine too");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(5)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            chatModelList.add(chatModel);
            chatModel=new ChatModel();
            chatModel.setId(String.valueOf(i)+"1");
            chatModel.setName("Ragini"+i);
            msg=new MessageModel();
            msg.setMsg("Hello");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(10)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Hi");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(9)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("How are you doing?");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(8)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("I am fine.");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(7)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("What about you?");
            msg.setMyMsg(true);
            date=new Date();
            date=new Date(date.getTime()-(6)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            msg=new MessageModel();
            msg.setMsg("Ya!I am fine too");
            msg.setMyMsg(false);
            date=new Date();
            date=new Date(date.getTime()-(5)*60000);
            msg.setDate(date);
            chatModel.addMessage(msg);
            chatModelList.add(chatModel);
        }
    }

    public static List<ChatModel> getPage(int pos){
        return chatModelList.subList(pos,pos+8);
    }

}
